import { Roboto } from "next/font/google";
import React from "react";

export const metadata = {
  title: "sign-up",
  description: "Generated by create next app",
};
const inter = Roboto({
  subsets: ["latin"],
  weight: "400",
});

export default function layout({ children }) {
  return <div className={inter.className}>{children}</div>;
}
